[project]
name = "wilderness"
requires-python = ">=3.8"
dynamic = ["version"]
dependencies = [
    "pandas>=2.0.3",
    "pyproj>=3.5.0",
    "rasterio>=1.3.11",
]

[dependency-groups]
dev = [
    "pandas-stubs>=2.0.3.230814",
    "ruff>=0.12.12",
]
